// Generated by CoffeeScript 1.7.1
(function() {
  var Boom, omit_keys, ref2resource, rename_keys, resource_uri;

  Boom = require('boom');

  resource_uri = require('./helpers').resource_uri;

  ref2resource = require('./helpers').ref2resource;

  omit_keys = require('./helpers').omit_keys;

  rename_keys = require('./helpers').rename_keys;

  module.exports = function(Model, path, options) {
    return function(req, res) {
      return Model.findOne(req.params, function(err, model) {
        if (err) {
          return res(Boom.notFound(err.message));
        }
        return model.remove(function(err) {
          var event;
          if (err) {
            return res(Boom.notAcceptable(err.message));
          }
          event = Model.modelName[0].toUpperCase() + Model.modelName.slice(1);
          req.server.emit('delete' + event, model);
          event = Model.collection.name[0].toUpperCase() + Model.collection.name.slice(1);
          req.server.emit('delete' + event, model);
          resource_uri(model, path, options.resource_key);
          ref2resource(model, options.refs);
          omit_keys(model, options.omit);
          rename_keys(model, options.rename);
          return res(model);
        });
      });
    };
  };

}).call(this);
