// Generated by CoffeeScript 1.7.1
(function() {
  var Boom, ref2resource, resource_uri;

  Boom = require('boom');

  resource_uri = require('./helpers').resource_uri;

  ref2resource = require('./helpers').ref2resource;

  module.exports = function(schema, path, options) {
    return function(req, res) {
      return schema.findOne(req.params, function(err, model) {
        if (err) {
          return res(Boom.notFound(err.message));
        }
        resource_uri(model, path, options.resource_key);
        ref2resource(model, options.refs);
        return res(model);
      });
    };
  };

}).call(this);
