// Generated by CoffeeScript 1.7.1
(function() {
  var Boom, ref2resource, resource_uri, _;

  _ = require('lodash');

  Boom = require('boom');

  resource_uri = require('./helpers').resource_uri;

  ref2resource = require('./helpers').ref2resource;

  module.exports = function(Model, path, options) {
    return function(req, res) {
      var limit, query, skip, sort, where;
      limit = req.query.limit || options.page_size;
      skip = req.query.skip || void 0;
      sort = req.query.sort || void 0;
      query = _.merge(req.query, req.params);
      where = _.transform(query, function(conditions, value, key) {
        var val;
        if (key !== 'limit' && key !== 'skip' && key !== 'sort') {
          val = JSON.parse(value);
          if (_.isObject(val)) {
            return conditions[key] = val;
          } else {
            return conditions[key] = value;
          }
        }
      });
      return Model.find(where).sort(sort).skip(skip).limit(limit).exec(function(err, models) {
        var model, _i, _len;
        if (err) {
          return res(Boom.badImplementation(err.message));
        }
        for (_i = 0, _len = models.length; _i < _len; _i++) {
          model = models[_i];
          resource_uri(model, path, options.resource_key);
          ref2resource(model, options.refs);
        }
        return res(models);
      });
    };
  };

}).call(this);
