// Generated by CoffeeScript 1.7.1
(function() {
  var isArray;

  isArray = Array.isArray || function(value) {
    return {}.toString.call(value) === '[object Array]';
  };

  module.exports = {
    ref2resource: function(model, refs) {
      var i, key, resource, val, _results;
      _results = [];
      for (key in refs) {
        resource = refs[key];
        if (isArray(model[key])) {
          _results.push((function() {
            var _ref, _results1;
            _ref = model[key];
            _results1 = [];
            for (i in _ref) {
              val = _ref[i];
              _results1.push(model._doc[key][i] = resource.path + '/' + val);
            }
            return _results1;
          })());
        } else {
          _results.push(model._doc[key] = resource.path + '/' + model[key]);
        }
      }
      return _results;
    },
    resource_uri: function(model, path, resource_key) {
      return model._doc.resource_uri = path + '/' + model[resource_key];
    },
    omit_keys: function(model, omit) {
      var key, _i, _len, _results;
      _results = [];
      for (_i = 0, _len = omit.length; _i < _len; _i++) {
        key = omit[_i];
        _results.push(delete model._doc[key]);
      }
      return _results;
    },
    rename_keys: function(model, rename) {
      var new_key, old_key, _results;
      _results = [];
      for (old_key in rename) {
        new_key = rename[old_key];
        model._doc[new_key] = model._doc[old_key];
        _results.push(delete model._doc[old_key]);
      }
      return _results;
    }
  };

}).call(this);
