// Generated by CoffeeScript 1.7.1
(function() {
  var Handler;

  Handler = (function() {
    function Handler(schema, path, options) {
      this.schema = schema;
      this.path = path;
      this.options = options;
    }

    Handler.prototype.find = function() {
      return require('./find')(this.schema, this.path, this.options);
    };

    Handler.prototype.find_one = function() {
      return require('./find_one')(this.schema, this.path, this.options);
    };

    Handler.prototype.create = function() {
      return require('./create')(this.schema, this.path, this.options);
    };

    Handler.prototype.update = function() {
      return require('./update')(this.schema, this.path, this.options);
    };

    Handler.prototype.destroy = function() {
      return require('./destroy')(this.schema, this.path, this.options);
    };

    return Handler;

  })();

  module.exports = Handler;

}).call(this);
