// Generated by CoffeeScript 1.7.1
(function() {
  var Boom, ref2resource, resource_uri;

  Boom = require('boom');

  resource_uri = require('./helpers').resource_uri;

  ref2resource = require('./helpers').ref2resource;

  module.exports = function(schema, path, options) {
    return function(req, res) {
      return schema.findOne(req.params, function(err, model) {
        if (err) {
          return res(Boom.notFound(err.message));
        }
        model.set(req.payload);
        return model.save(function(err) {
          var event;
          if (err) {
            return res(Boom.notAcceptable(err.message));
          }
          event = schema.modelName[0].toUpperCase() + schema.modelName.slice(1);
          req.server.emit('update' + event, model);
          event = schema.collection.name[0].toUpperCase() + schema.collection.name.slice(1);
          req.server.emit('update' + event, model);
          resource_uri(model, path, options.resource_key);
          ref2resource(model, options.refs);
          return res(model);
        });
      });
    };
  };

}).call(this);
