// Generated by CoffeeScript 1.7.1
(function() {
  var Handler, Resource, Router, _;

  _ = require('lodash');

  Handler = require('./handler');

  Router = require('./router');

  Resource = (function() {
    function Resource(schema, path, options) {
      var default_options;
      default_options = {
        resource_key: "_id"
      };
      this.path = path;
      this.options = {};
      _.merge(this.options, default_options, options);
      this.handler = new Handler(schema, this.path, this.options);
      this.router = new Router(this.path, this.handler, this.options);
    }

    return Resource;

  })();

  module.exports = Resource;

}).call(this);
