// Generated by CoffeeScript 1.7.1
(function() {
  var Router;

  Router = (function() {
    function Router(path, handler, options) {
      var resource_key, single_path;
      this.handler = handler;
      this.options = options;
      resource_key = this.options.resource_key;
      single_path = "" + path + "/{" + resource_key + "}";
      this.routes = [
        {
          method: "GET",
          path: single_path,
          config: {
            handler: this.handler.find_one()
          }
        }, {
          method: "GET",
          path: path,
          config: {
            handler: this.handler.find()
          }
        }, {
          method: "POST",
          path: path,
          config: {
            handler: this.handler.create()
          }
        }, {
          method: "UPDATE",
          path: single_path,
          config: {
            handler: this.handler.update()
          }
        }, {
          method: "DELETE",
          path: single_path,
          config: {
            handler: this.handler.destroy()
          }
        }
      ];
    }

    return Router;

  })();

  module.exports = Router;

}).call(this);
